#!/bin/bash

echo "🚀 Pushing to GitHub: A-B-testing-App"
echo "======================================"
echo ""
echo "Repository: https://github.com/Prasanth14-afk/A-B-testing-App"
echo "Branch: main"
echo "Commits to push: 3"
echo ""
echo "📦 What will be uploaded:"
echo "  ✅ New dashboard-app/ (32+ files)"
echo "  ✅ All documentation"
echo "  ✅ Python analysis files"
echo "  ✅ CSV data outputs"
echo ""
echo "⚠️  Authentication Required:"
echo "  When prompted for password, use your GitHub Personal Access Token"
echo "  (NOT your GitHub password)"
echo ""
echo "📝 To create a token:"
echo "  1. Go to: https://github.com/settings/tokens"
echo "  2. Click 'Generate new token (classic)'"
echo "  3. Select 'repo' scope"
echo "  4. Copy and use as password"
echo ""
read -p "Press Enter to push to GitHub..."
echo ""

cd "/Users/prasanthkumar/Desktop/A:B testing"
git push origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ SUCCESS! Repository pushed to GitHub!"
    echo ""
    echo "🌐 View your repo at:"
    echo "   https://github.com/Prasanth14-afk/A-B-testing-App"
    echo ""
    echo "📊 Your dashboard is now on GitHub!"
else
    echo ""
    echo "❌ Push failed. Common solutions:"
    echo ""
    echo "1. Create Personal Access Token:"
    echo "   https://github.com/settings/tokens/new"
    echo ""
    echo "2. Or use GitHub Desktop:"
    echo "   - Open GitHub Desktop"
    echo "   - Add repository"
    echo "   - Click 'Push origin'"
    echo ""
    echo "3. Or use VS Code:"
    echo "   - Open Source Control panel"
    echo "   - Click '...' menu → Push"
fi
